# Generated by Django 3.1.7 on 2021-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210317_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/640x510.png', null=True, upload_to=''),
        ),
    ]
